import { Inter } from "next/font/google";
import "./globals.css";

 import Navbar2 from "@/Component/Navbar/Navbar";
 import 'bootstrap/dist/css/bootstrap.min.css';
 import Footer from "@/Component/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar2></Navbar2>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
